name: LinkGrabber

on:
  schedule:
    - cron: '0 */3 * * *'
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  runCode:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5   # 从 v4 升级到 v5，原生支持 Node.js 24
      
      - name: Grab Link
        run: |
          git config --global user.email "dp247@hll.localhost"
          git config --global user.name "dp247"
          chmod +x exec_grabber.sh && ./exec_grabber.sh
          git add -A
          git commit -m "Auto-update youtube.m3u8" || echo "没有需要提交的更改"
          git push --force-with-lease
